### ISSUE TITLE
Indexes mismatches for filling empty values in the velocity model

### ISSUE THREAD

**Issue by SeismoFelix** [thurinj/specfem_tomo_helper#1]
Hi
 I am using the code to extrapolate a [3D velocity model](http://ds.iris.edu/ds/products/emc-midd_east_crust_1/) with some empty values. 

When I try to load a variable I got the following error: 

`data = nc_model.load_variable('vs',fill_nan=False)
  File "/Users/felix/specfem_tomo_helper/specfem_tomo_helper/fileimport/ncimport.py", line 69, in load_variable
    var_data[var_mask] = np.nan
IndexError: boolean index did not match indexed array along dimension 0; dimension is 121, but corresponding boolean dimension is 24`

I think this is because in [ncimport.py](https://github.com/thurinj/specfem_tomo_helper/blob/main/specfem_tomo_helper/fileimport/ncimport.py#L62) var_data is rotated, but  var_mask is not. Therefore there is a mismatch in the indexes [when filling the empty values of the array with np.nan](https://github.com/thurinj/specfem_tomo_helper/blob/main/specfem_tomo_helper/fileimport/ncimport.py#L65). 

 The velocity model used as an [example](https://ds.iris.edu/ds/products/emc-csem_europe/) for this script does not contain empty values, and hence, the error does not occur.   I have tried with different [velocity models](https://ds.iris.edu/ds/products/emc-eav09/) with empty values and the script yields the same error.

I suggest moving the [if for rotating](https://github.com/thurinj/specfem_tomo_helper/blob/main/specfem_tomo_helper/fileimport/ncimport.py#L61) at the bottom after filling the array with np.nan.  

Thanks, 

Félix

**Comment by thurinj** [comment]
Hi Felix,

Thanks for raising the issue, I'll have a look at it asap.

To the best of my recollection, the Fill Nan parameters take values from the bottom-up to fill the upper portion of the model that might contain NaNs values close to the surface. It should be able to manage gaps or holes in the model, as long as there's a non-empty cell underneath said gap. This option does not extrapolate in the lateral direction though, so that's something that might be playing here.

I tried the value filling in the SCEC CVM model, which has NaN values on all the shallow portions, and it didn't get me any errors.

Could you share the model you are trying to interpolate with me or find a publicly available model on which I can check the error?

**Comment by SeismoFelix** [comment]
Thanks, Julien for addressing my issue. You can find the model here: http://ds.iris.edu/ds/products/emc-midd_east_crust_1/  . I am still thinking about some gaps I see after interpolating (see attachment) but there is data in the actual velocity model. Did you put some constraints for accepting isolated points? Thanks. 
![Extrapolated_3D_VM_Iran](https://user-images.githubusercontent.com/18186011/171759967-d9ac9234-6ddd-4f47-abe5-e1043819bd43.png)
<img width="704" alt="Slice_3D_VM_Iran" src="https://user-images.githubusercontent.com/18186011/171760028-f97ff53b-5f9b-40b0-a113-e959e37750ea.png">

**Comment by thurinj** [comment]
I integrated the suggestion you made in your first post, so filling the NaN values from the bottom-up is done prior to rotating the data array (if needed). 
The second part raised in this issue (extrapolating model parameters in largely empty sections of the domain) is not yet in the scope of the code so I am closing this issue.
